### ISSUE TITLE
Show "recently updated" on  home screen

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-app#139]
Maybe add option to display recently updated items on the home screen.

- Parts?
- StockItems?
- Orders?

Similar to the home page on the web server..

**Comment by matmair** [comment]
@SchrodingersGat no intrest in this anymore or already implemented?

**Comment by SchrodingersGat** [comment]
Closed due to expanding scope of what constitutes a "recent update". The current UI provides decently fast access to most functionality. Maybe once we overhaul the web dashboard we'll have some better ideas here.
