### ISSUE TITLE
Not valid QR Code

### ISSUE THREAD

**Issue by lettore** [inventree/inventree-app#161]
I was used to scan the QR codes of items in inventory but suddenly it not works anymore as it says that the code is invalid. Inventree server version 0.6.0

**Comment by SchrodingersGat** [comment]
@lettore server `0.6.0` is quite old it is possible something has changed in the app.

- What version of the app are you running
- What is the "context" when you are scanning codes. Just scanning the code of a stock item?
- Can you provide a screenshot of the error message?

**Comment by lettore** [comment]
Scanning stocks and locations, what was working before ( I admit I was not using Inventree for some months).
Updating to stable version resolved.
