### ISSUE TITLE
Scanning location into location

### ISSUE THREAD

**Issue by KingGeorgThe3rd** [inventree/inventree-app#163]
Hello,

we recently started using Inventree and I am pretty impressed with what you people did there. I am looking for a new feature but for some reason, I didn't find this suggestion yet so I'd like to make a suggestion here.

Basically what I am looking for is to scan a location into a location. The reason is that I have boxes that are packed and put on shelves. The boxes are themselves locations that have barcodes on them. 
I can put the code on the box and then use the drop-down menu under the edit function to change the location. However, I find this personally cumbersome. Having barcodes on the shelves I could scan the box and then the code on the shelf for this operation which would be a lot faster.

For this, I suggest putting the transfer symbol next to the parent folder shown in the app as can be seen in the mockup below. Once you scan the box the screen shows up. I then click the transfer symbol next to the parent location opening the barcode scanner. I scan the location and with this information, the app changes the parent location accordingly.

![InventreeMockup](https://user-images.githubusercontent.com/59980161/177278639-1e715b7a-34fd-4e0c-871a-96c466aee72c.jpg)

**Comment by SchrodingersGat** [comment]
This is a fantastic idea! I will see what I can do.

**Comment by SchrodingersGat** [comment]
@KingGeorgThe3rd this has now been implemented and you should see the new version (0.8.0) pushed out reasonably soon.

**Comment by KingGeorgThe3rd** [comment]
Awesome, many thanks.
