### ISSUE TITLE
Delete User Data

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-app#166]
Provide user with option to delete all their data

**Comment by matmair** [comment]
@SchrodingersGat would that be an interesting feature for the webapp as well?

**Comment by SchrodingersGat** [comment]
The browser already offers users the ability to delete any cached data, I'm not sure what we would offer beyond that.

**Comment by matmair** [comment]
@SchrodingersGat I mean an API endpoint and UI function to clean out all data for a user from an instance.

**Comment by SchrodingersGat** [comment]
I'm not sure if that is a good idea.. Deleting the user would achieve that, but the user should not be able to "delete" themselves as it removes a whole lot of information from many points in the database.

Is there any pertinent user data besides what is stored in the database?

**Comment by matmair** [comment]
@SchrodingersGat I would consider especially the session data to be covered by right to deletion on request as of GDPR. So a tool delete that data would be nice. I do not think there is any other data like that (except for the user itself).

**Comment by SchrodingersGat** [comment]
session data is a good example :)

**Comment by matmair** [comment]
@SchrodingersGat nearly seems like I deal with stuff like that a lot at work ;-)

**Comment by SchrodingersGat** [comment]
I am closing this out now, the app no longer stores username / password, and the API token can be explicitly deleted. Nothing else much is cached internally either.
