### ISSUE TITLE
Check Stock Items into Location returns 201 Code

### ISSUE THREAD

**Issue by markxoe** [inventree/inventree-app#194]
Using the QR code scanner (Home -> Stock -> (any Stock Location) -> Actions -> Check Stock Items into Location) to check items into some location returns an 201 code, which the app interprets as an error.

(My phone is set to German so said location is probably not 100% right)

**Comment by SchrodingersGat** [comment]
Hi what version of the app are you running?

And on iOS or Android?

**Comment by markxoe** [comment]
Hi, I am running the iOS app, version 0.7.2

**Comment by SchrodingersGat** [comment]
@markxoe I have just now (in the last hour) released `0.8.0` for iOS which fixes this issue. Please report back once your app has updated and LMK if the issue has been resolved!

**Comment by markxoe** [comment]
Okay perfect, didn't see it in the changelog, thanks! (I'll close this as soon as I have the update)

**Comment by SchrodingersGat** [comment]
@markxoe did the update come through? Does this work now?

**Comment by SchrodingersGat** [comment]
@markxoe assuming this worked, closing the issue :)
