### ISSUE TITLE
[FR] View, allocate & ship Sales Orders

### ISSUE THREAD

**Issue by snorkrat** [inventree/inventree-app#203]
Would love the functionality of at least viewing sales orders and their items. 

Ideally I would love to be able to allocate stock, create a shipment and complete a sales order. 

However, simply viewing the SO and the items within would allow me to pick the items and get them ready for dispatch.

**Comment by SchrodingersGat** [comment]
Good idea. Integrating barcode support would be useful for scanning items into the sales order.

Do you have any flutter experience or motivation to work on this?

**Comment by snorkrat** [comment]
> Good idea. Integrating barcode support would be useful for scanning items into the sales order.
> 
> Do you have any flutter experience or motivation to work on this?

Unfortunately I don't have any dev experience!

**Comment by alaskancode** [comment]
This seems like a pretty major gap in the product. Being able to receive and move inventory, but not ship it, is kind of a big hole.

Has any progress been made on bulding this set of features in the mobile app? They seem to work pretty well in desktop browser app, so how hard can it be to put this in the mobile interface?

**Comment by SchrodingersGat** [comment]
>Has any progress been made on bulding this set of features in the mobile app? 

No. But it's just using the API, so would be entirely possible. 

The workflow for sales orders is a bit more complex than purchasing, which is mainly why I've been holding off on this. Also, no time!

**Comment by snorkrat** [comment]
> > Has any progress been made on bulding this set of features in the mobile app?
> 
> No. But it's just using the API, so would be entirely possible.
> 
> The workflow for sales orders is a bit more complex than purchasing, which is mainly why I've been holding off on this. Also, no time!

I appreciate you probably have a lot on your plate, but just checking in to see if there has been any progress on this?

**Comment by SchrodingersGat** [comment]
@snorkrat you're not wrong about the plate :) would you be willing to either implement or sponsor such a feature?

**Comment by snorkrat** [comment]
> @snorkrat you're not wrong about the plate :) would you be willing to either implement or sponsor such a feature?

I actually manage my InvenTree instance for a friend.  How much would sponsoring this feature be?

**Comment by SchrodingersGat** [comment]
@snorkrat send me an email at support@inventree.org and we can discuss further :) I do not think it will be too difficult to implement

**Comment by lippoliv** [comment]
I'm about to get into InvenTree. My wife has a small business and we do, beside online selling, also sell on big events. Currently we use sumup to track down stock movements and do payments. But it's to inefficient.

My long-time goal with InvenTree is, that we can use it to at least track stock movements, the scanner is a central place here to "build" sales orders quickly.

I'll ping you per mail as well.

**Comment by SchrodingersGat** [comment]
@lippoliv progressing well - see:

- https://github.com/inventree/inventree-app/issues/451
- #461 
- https://github.com/inventree/inventree-app/pull/464

**Comment by snorkrat** [comment]
Great to see this progressing well! Is the ability to allocate stock the last part to do?

**Comment by SchrodingersGat** [comment]
Yep, hoping to get to this by end of next week :)

**Comment by SchrodingersGat** [comment]
@snorkrat check out the incoming PR - https://github.com/inventree/inventree-app/pull/466

Once this is finished and merged, the new release will be out soon

**Comment by snorkrat** [comment]
> @snorkrat check out the incoming PR - #466
> 
> Once this is finished and merged, the new release will be out soon

Awesome! I just got a notification that you'd completed this which is awesome! Hopefully it doesn't take too long for the new app to get approved/released :). Thanks again for the swift work!
