### ISSUE TITLE
Barcode assigning/deassigning feature is missing in version 0.9.0

### ISSUE THREAD

**Issue by MR-DOS** [inventree/inventree-app#231]
In the newest version 0.9.0 on Android, the feature which allowed assigning and deassigning barcodes to stock items, is missing. The button for these actions is simply gone.

Sadly, this change/bug renders the app completely useless for me.

**Comment by SchrodingersGat** [comment]
@MR-DOS this is certainly not intended! Please provide:

- A screenshot of the app screen where these buttons should normally be
- The version of the InvenTree server you are connecting to.

**Comment by MR-DOS** [comment]
There is only one place where these buttons were, the Stock Item Actions view and I think you already patched it by looking at the latest commits.
Inventree server 0.8.3.

![image](https://user-images.githubusercontent.com/29711626/206918241-8cecfce9-bd57-487b-a000-d2d25eeac39e.png)

**Comment by SchrodingersGat** [comment]
Please let me know if the new update fixes the issue on your end :)
