### ISSUE TITLE
Support for icons in PartCategory and StockLocation

### ISSUE THREAD

**Issue by wolflu05** [inventree/inventree-app#234]
Hello,

https://github.com/inventree/InvenTree/pull/3542 added the ability to associate icons with a PartCategory or StockLocation. The app is lacking of the functionality to:
1. display the icons before the names
2. edit the icons

On a Webbrowser adding icons is easy through font awesome. However I have no experience with dart and flutter I would think that this seems like a hard request because its firstly not easy to load font awesome into flutter and secondly maybe we need to convert the css classes into some icon names.

**Comment by SchrodingersGat** [comment]
The app already uses the fontawesome icon set, the hard part (maybe) would be converting the name of the icon into the internal icon..

**Comment by SchrodingersGat** [comment]
The underlying fontawesome library has a file with all the defined icons:

![image](https://user-images.githubusercontent.com/10080325/208233656-4d609827-1457-459d-b61f-af8dc42a1d5d.png)

It's a complete hack but maybe a script to generate a lookup table from the icon "name" (in the InvenTree API) to an internal icon representation?

**Comment by wolflu05** [comment]
One idea would also be to use the hex representation for a map, because I guess they are the same in your screenshot and the fontawesome page.

**Comment by SchrodingersGat** [comment]
Yes, looks that way: https://fontawesome.com/v5/icons/boxes?s=solid&f=classic

**Comment by wolflu05** [comment]
That was fast, didn't expected that. Thank you very much. 🚀
