### ISSUE TITLE
Feature: Sales Orders

### ISSUE THREAD

**Issue by SjamonDaal** [inventree/inventree-app#236]
I would like to be able to see what is sold to be able to get some kind of picking order, option to mark items as picked, add shipping information etc.

This way the app could also be used when walking tough the warehouse to pick all required items.

**Comment by SchrodingersGat** [comment]
Thanks @SjamonDaal - I think this a duplicate of https://github.com/inventree/inventree-app/issues/203

**Comment by SjamonDaal** [comment]
@SchrodingersGat yep, thanks
