### ISSUE TITLE
Bug: Action Notifications covers buttons

### ISSUE THREAD

**Issue by SjamonDaal** [inventree/inventree-app#239]
When performing any action that returns a status update a green on red notification bar appears on the bottom of my screen. This covers the Home, Search and Notifications buttons completely.

This is really annoying because users are unable to touch those buttons for ±5 seconds and have to wait.

I think a simple solutions would be to imidiently hide the notification when the user taps on it. This still allows the user to read the notification but also allows the user to tap the notification and quickly continues to work and use the buttons again. We use the search button a ton so this would be really helpful!

![Screenshot_20221221-220456](https://user-images.githubusercontent.com/4325936/209002570-e32ae72a-c55d-486e-a8bf-edacddc17fad.png)

**Comment by SchrodingersGat** [comment]
@SjamonDaal thanks for the suggestion - this will be fixed in https://github.com/inventree/inventree-app/pull/240
