### ISSUE TITLE
Bug: Pop-up doesn't close

### ISSUE THREAD

**Issue by SjamonDaal** [inventree/inventree-app#241]
When opening a purchase order and long press a line item a pop-up appears to mark something as received. When pressing the back button (or making the back gesture) the pop-up doesn't close. Restarting the app is required to close the pop-up.

![Screenshot_20221226-151342](https://user-images.githubusercontent.com/4325936/209557710-da0ffccc-c0df-449f-b9f6-3cd9e8d6a760.png)

**Comment by SchrodingersGat** [comment]
@SjamonDaal thanks for reporting. Does the popup close if you press on a different area of the screen?

**Comment by SjamonDaal** [comment]
Yes it does.
