### ISSUE TITLE
building the app ourselves vs purchasing it?

### ISSUE THREAD

**Issue by AndyADD** [inventree/inventree-app#245]
As dumb as this sounds, is this allowed? It seems you have everything needed for user to compile/build the app, but I noticed on the google play store it costs money, so I assume that's more of a convenience or support the devs "fee"?

**Comment by SchrodingersGat** [comment]
There's nothing stopping this, but the small purchase fee is one of the only ways that inventree is supported financially. If you do build it yourself, it would be appreciated if you sponsor the project ☺️
