### ISSUE TITLE
unknown response when scanning barcode assigned to a supplier part

### ISSUE THREAD

**Issue by EthanTheMathmo** [inventree/inventree-app#246]
I have barcodes assigned to supplier parts which have arrived in stock, and ideally would be able to scan them on the app. While the api response works (returning that a match was found, and giving the supplier part), the app gives an 'Unknown Response' message, rather than taking me to the supplier part in question

**Comment by matmair** [comment]
@EthanTheMathmo the main maintainer of the repo is currently not available but I will try to help triage with more information.
1. What version is your server running? Maybe post the version information here.
2, What version of the app your running?

**Comment by EthanTheMathmo** [comment]
server: 0.10.0
app: 0.9.2, build 52

**Comment by matmair** [comment]
@EthanTheMathmo are you running the development version? Last stable release is 0.9.2

**Comment by EthanTheMathmo** [comment]
I think so - just got it running yesterday. Is this behaviour unexpected? (i.e., is there support for supplier barcodes on the app in the last stable version?) In which case, I'll reinstall

**Comment by matmair** [comment]
It should work either way. But latest tends to break more often as not everything is e2e tested.

I will look into it in the coming days, we might have a bug at our hands.

**Comment by EthanTheMathmo** [comment]
I changed to the stable version and still not working. The response I’m
shown on the mobile app is attached below.

**Comment by matmair** [comment]
@EthanTheMathmo this seems to be an issue with the app, we will have to wait till the maintainer is online again - please be patient for a few days.

**Comment by EthanTheMathmo** [comment]
No worries - I found a temporary workaround for my use case.

**Comment by SchrodingersGat** [comment]
@EthanTheMathmo thanks for reporting this. Currently the app does not "know" about supplier parts - which is why it is reporting an unknown response here. I'll add support for supplier parts in for the next release of the app :)

**Comment by SchrodingersGat** [comment]
@EthanTheMathmo this has now been  implemented in https://github.com/inventree/inventree-app/pull/253

This feature will be released soon in 0.10.0

**Comment by EthanTheMathmo** [comment]
awesome, thank you.
