### ISSUE TITLE
[FR] Always accessible Menu-Icon

### ISSUE THREAD

**Issue by simonkuehling** [inventree/inventree-app#264]
For quick access of all menu entry points in the app, it would be useful to have quick access to the main menu from throughout the app.

Right now I always have to step back through the history completely until reaching the main menu again. A menu icon could fit nicely into an always-visible top navigation bar that can also have a camera-button like suggested in https://github.com/inventree/inventree-app/issues/263

**Comment by SchrodingersGat** [comment]
You can "long press" the back button on most screens to access the global menu:

https://docs.inventree.org/en/latest/app/connect/#drawer-menu - perhaps this should be documented a bit more clearly?

Is this sufficient do you think?

**Comment by simonkuehling** [comment]
Oh, did not know about that - functionality-wise that is exactly what I was missing... The long press does still introduce a little too much friction for my efficiency taste, since pretty much every time the app is opened this would be the first thing to do.

I also don't think it is likely that a new user will find that menu without actually reading the docs first - and, well, who does that, right? ;-)

**Comment by SchrodingersGat** [comment]
Agreed that it's not the most efficient, but was the "cleanest" solution I could come up with. Maybe there's a better way? A visible menu icon would work too and I'd be happy to entertain that

**Comment by simonkuehling** [comment]
Maybe the top-right corner could be the place for an always visible menu icon? On the home screen this would compete with the servers list icon right now - but since that is already accessible through `Menu > Settings > Server` and is probably used much less frequenty, I think that could be sacrificed for consistency...

**Comment by SchrodingersGat** [comment]
There are many other screens which use the top right corner - these would all need to be addressed also!

**Comment by simonkuehling** [comment]
Oh, that's right - didn't even check that to verify...

Well, having thought about it a little more: besides missing a visual cue for it, the drawer menu does work very well for all menu items besides the camera access. It is indeed mostly the instant access to the barcode camera that could be improved...

What about an always visible [Scan Barcode] button at the lower end of the screen, below the actions menu? My iPhone12 has more than enough screen estate for that - but I'm not sure how the situation on smaller screens looks... Could also be a configuration option to show/hide that button. I'm sure not all users fully run on QR codes with InvenTree...

**Comment by SchrodingersGat** [comment]
@simonkuehling the upcoming app release has a globally accessible "barcode scan" button now btw :)

**Comment by simonkuehling** [comment]
Uh nice! 🤗
