### ISSUE TITLE
[BUG] camera freezes after scanning into location via QR code (iOS)

### ISSUE THREAD

**Issue by simonkuehling** [inventree/inventree-app#265]
When scanning StockItems into a location, the camera on iOS (iPhone12, iOS 16.1.2) often randomly freezes for me. If it happens, it always has just successfully detected a QR code and did indeed issue the move operation correctly. Hitting the `<` to go back and re-opening the camera always works.

Not sure how to further debug this - any tips?

**Comment by simonkuehling** [comment]
I noticed today that the QR-code scanner sometimes registers multiple times quickly after another when opening some view from a scan. The `barcodeSuccessTone();` gets played more than once in these cases while switching to the view...

This can also pretty reliably be reproduced if you scan multiple QR codes at the same time (all in the camera view together)

Seems like a successful scan does not block further scans fast enough through `_controller.pauseCamera()` - maybe this is the same cause for the freeze from above?

I am looking at these lines - we could add a boolean state variable like `currently_processing` to prevent processing multiple scan results concurrently..? 

https://github.com/inventree/inventree-app/blob/5c06e3c9de489afa62a4a0e9d44ad25f3f10b2e1/lib/barcode.dart#L670-L676

```dart
    bool currently_processing = false;
    controller.scannedDataStream.listen((barcode) {
      if (!currently_processing) {
        currently_processing = true;
        _controller?.pauseCamera();


        if (barcode.code != null) {
          widget._handler.processBarcode(_controller, barcode.code ?? "");
        }
        currently_processing = false;
      }
    });
```

...which is similar to what someone else already tried as working - should have searched first...
https://github.com/juliuscanute/qr_code_scanner/issues/11#issuecomment-669163641

**Comment by SchrodingersGat** [comment]
@simonkuehling thanks for proposing a solution! I'll have a look into this

**Comment by SchrodingersGat** [comment]
@simonkuehling check out the implementation in simonkuehling - LMK what you think

**Comment by simonkuehling** [comment]
I can't test it, but looks solid to me - clean code!
