### ISSUE TITLE
[FR/Improvement] Do not show green QR-scan-success banner when opening a view

### ISSUE THREAD

**Issue by simonkuehling** [inventree/inventree-app#266]
When scanning QR codes that read successfully and open a specific view (Part, StockItem, StockLocation etc), the green confirmation banner that slides up from the bottom covers the action buttons for a second. I think that banner should be omitted if the app leaves the camera screen and opens a view - which is confirmation of a successful read in itself. That would remove the unnecessary delay before being able to interact with that view after scanning.

As a confirmation in those cases, where the camera stays open (i.e. when scanning multiple StockItems into a location), the confirmation banner does have its value, though.

**Comment by SchrodingersGat** [comment]
This makes sense - do you want to submit a PR?

**Comment by simonkuehling** [comment]
Sure, I gave it a good guess at PR https://github.com/inventree/inventree-app/pull/267 ;-)
