### ISSUE TITLE
Support new types of barcode results

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-app#294]
Ref: https://github.com/inventree/InvenTree/pull/4575

**Comment by superbeppe98** [comment]
Hi,
I see that currently in the iOS app I can't scan UPC-A codes, but the same code in code-128 format is scanned fine.
Is there an ETA for reading a wider range of barcodes?

**Comment by matmair** [comment]
This issue is not about supporting other barcode types but inventree types that now support barcodes attached to them.
Submitting a PR for additional barcode types will set an ETA for more barcodes ;-)

**Comment by SchrodingersGat** [comment]
@superbeppe98 I've opened a new issue for you
