### ISSUE TITLE
Add dismiss button for keyboard on opened search view

### ISSUE THREAD

**Issue by wolflu05** [inventree/inventree-app#303]
After opening the search view, there is no way to get to the icons at the bottom, as there is no way close the keyboard. 

There should be a dismiss button and the keyboard should also close after pressing search.

https://user-images.githubusercontent.com/76838159/230744147-55b04051-3dad-43e5-9bfd-22089da0ab36.MOV

**Comment by SchrodingersGat** [comment]
@wolflu05 are you on iOS or Android? I cannot reproduce this on 3x Android devices so far

**Comment by wolflu05** [comment]
I am on an iPhone X with ios on build 57 (0.10.2).

**Comment by SchrodingersGat** [comment]
Looks like this issue is specific to iOS (and the way that the keyboard is rendered). There may be a way around this, I will look into it.

**Comment by wolflu05** [comment]
Ok, Thanks for the quick fix.
