### ISSUE TITLE
Darkmode 

### ISSUE THREAD

**Issue by horbix28** [inventree/inventree-app#316]
Is there any plan on Implementing a dark mode for rhe mobile app already?

**Comment by SchrodingersGat** [comment]
@horbix28 no plan but it's a nice idea! Would you be able to contribute something like this?

**Comment by horbix28** [comment]
Unfortunately i dont have much plan of java development and android apps.

**Comment by SchrodingersGat** [comment]
Good news then, the app is developed in dart ;)

I'll take a look, doesn't seem too difficult to implement.
