### ISSUE TITLE
Android app not compilable could you guys help me?

### ISSUE THREAD

**Issue by anonkwe** [inventree/inventree-app#356]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':device_info_plus'.
> Could not resolve all files for configuration ':device_info_plus:classpath'.
   > Could not find kotlin-util-klib-1.7.22.jar (org.jetbrains.kotlin:kotlin-util-klib:1.7.22).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/org/jetbrains/kotlin/kotlin-util-klib/1.7.22/kotlin-util-klib-1.7.22.jar
   > Could not find kotlin-annotation-processing-gradle-1.7.22.jar (org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.7.22).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/org/jetbrains/kotlin/kotlin-annotation-processing-gradle/1.7.22/kotlin-annotation-processing-gradle-1.7.22.jar
   > Could not find kotlin-build-common-1.7.22.jar (org.jetbrains.kotlin:kotlin-build-common:1.7.22).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/org/jetbrains/kotlin/kotlin-build-common/1.7.22/kotlin-build-common-1.7.22.jar
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':device_info_plus' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':device_info_plus' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by matmair** [comment]
@anonkwe do you have a fully functioning kotlin setup?

**Comment by anonkwe** [comment]
that's what i'd like to know to be honest  @matmair

**Comment by matmair** [comment]
It is hard to tell without knowing what you did. Did you set up Flutter following the official [getting started](https://docs.flutter.dev/get-started/install) or did you follow other docs to get the dev environment set up? Also on what plattform and for which target platform are you running?

**Comment by anonkwe** [comment]
@matmair yes that's exactly what i did for flutter.  for kotlin here:
![image](https://github.com/inventree/inventree-app/assets/61838766/fa52e740-ec06-4496-9372-bf174a455ad2) 



its also telling me Could not get unknown property 'android' for project ':device_info_plus' of type org.gradle.api.Project.

**Comment by matmair** [comment]
@anonkwe so you are building for Android - I have it only working on mac for iOS so not sure if it is a android thing. It sounds like [this problem on SO](https://stackoverflow.com/questions/57439197/could-not-get-unknown-property-android-for-root-project-android-of-type-org). Could you check if that answer helps?

**Comment by SchrodingersGat** [comment]
@anonkwe it looks like you don't have the right version of kotlin installed - does [this link](https://stackoverflow.com/questions/45158803/how-to-configure-kotlin-version-in-android-studio) help?

Please post your versions of the following:

- kotlin
- flutter
- dart
- android-studio

**Comment by anonkwe** [comment]
@SchrodingersGat  ill try with a mac vm i guess


kotlin:231.1.8.21.IJ9011.34
flutter:3.10.1
dart:  3.01
android-studio: 2022.2

**Comment by SchrodingersGat** [comment]
@anonkwe I have the following development setups working:

- Windows / vscode
- mac / Android studio

Both without issue. I'll check versions on my setup later on.

**Comment by anonkwe** [comment]
@SchrodingersGat @matmair locales stuff are a nightmare, i cant seem to debug, do you have a trick

**Comment by SchrodingersGat** [comment]
My versions:

| App | Version | 
| --- | --- |
| Flutter | 3.7.3 |
| Dart | 2.19.2 |
| kotlin | 213-1.7.20-release-for-android-studio-AS6777.52 |
| android-studio |  2021.3.1 Patch 1 |

**Comment by SchrodingersGat** [comment]
@anonkwe start by getting the same versions of flutter / dart / kotlin installed.

Most likely it is the kotlin version mismatch which is the issue here

**Comment by anonkwe** [comment]
@SchrodingersGat what are all the sdk'S that you specify

**Comment by SchrodingersGat** [comment]
Do you mean in the table listed above or something else?

**Comment by anonkwe** [comment]
@SchrodingersGat no its all good for that, i mean your inventree project structure

**Comment by SchrodingersGat** [comment]
That should all be in the git project. All the required versions are hard-coded into [pubspec.lock](https://github.com/inventree/inventree-app/blob/master/pubspec.lock)

**Comment by anonkwe** [comment]
@SchrodingersGat i'm in the same exact environment as you are, still unable to deploy cause of locales and its variables 
![image](https://github.com/inventree/inventree-app/assets/61838766/543bde70-14c9-408a-8426-6cc02050b4d5)

**Comment by SchrodingersGat** [comment]
Ah! You need to compile the translations. Run `invoke translate` from the top level directory.

**Comment by anonkwe** [comment]
@SchrodingersGat pardon my rookie skills, but how do i exactly run this on an android projetct?

![image](https://github.com/inventree/inventree-app/assets/61838766/cffae472-5ea3-4145-92a2-40db53dfe28d)

**Comment by SchrodingersGat** [comment]
My mistake, you will need to install "invoke" first:

`pip install invoke`
or
`python3 -m pip install invoke`

**Comment by SchrodingersGat** [comment]
Looks like the setup guide needs some work ;)

**Comment by anonkwe** [comment]
im sorry @SchrodingersGat, I really appreciate it tho

**Comment by anonkwe** [comment]
me again -_- , really sorry, i still get the not found command, what am i missing? also to get the dependencies, i need to modify the   arb-dir path from lib/l10n/collected to lib/l10n... Again, excuse my rookie skills, but if I can get it to compile, I'll finally be able to build


![image](https://github.com/inventree/inventree-app/assets/61838766/f2155287-7b73-4a53-9e67-b31d4c735122)

**Comment by SchrodingersGat** [comment]
You might have to exit the program and then re open after you've installed invoke?

**Comment by anonkwe** [comment]
@SchrodingersGat  just did that! even tho i do i need to specify something somewhere?

![image](https://github.com/inventree/inventree-app/assets/61838766/369dd5dd-e4ee-4e3b-a47e-ce6129d97db4)

**Comment by wolflu05** [comment]
You restarted your terminal? Maybe you can also try python3 -m invoke translate

**Comment by anonkwe** [comment]
@wolflu, didnt even install python on my vm at first -_- my bad

**Comment by wolflu05** [comment]
Is it working now?

*Btw. you pinged the wrong user (wish I could claim that name, but no success yet).*

**Comment by anonkwe** [comment]
@wolflu05 ahaha kinda went fast.. yeah everything looks good for now, only thing is the sentry_dsn.dart ... what's up with that? do I take the sentry_dummy instead?

**Comment by anonkwe** [comment]
it finally compiles tho! thanks a lot @SchrodingersGat  @wolflu05 for the precious help, much appreciated

**Comment by SchrodingersGat** [comment]
@anonkwe glad you got it working!

The setup instructions definitely need work. Can you please submit a PR with some updates to README.md to include the undocumented steps you had to take to get the dev environment working?

**Comment by SchrodingersGat** [comment]
@anonkwe aside from the documentation issue are you happy to close this issue out now?

**Comment by anonkwe** [comment]
yep, will close it sorry for the delay @SchrodingersGat
