### ISSUE TITLE
APK Binary for android

### ISSUE THREAD

**Issue by damien-ls** [inventree/inventree-app#359]
It would be great to have the APK binary for android, as we have barcode scanner with integrated android, but those can't access the playstore (no account, intranet, etc..).

Can build from the source but that requires installing the whole android toolchain.

**Comment by SchrodingersGat** [comment]
@damien-ls what sort of scanner hardware do you have? Have you seen the work being done in https://github.com/inventree/inventree-app/issues/344

**Comment by damien-ls** [comment]
@SchrodingersGat It is a similar scanner but not Zebra. It just sends plain text like a keyboard input.

#344 seems a long way off, although the android app should work out of the box.

**Comment by damien-ls** [comment]
To the addition of that, we have location in China, which the android playstore is not accessible so even for the users they won't be able to install the app.

**Comment by SchrodingersGat** [comment]
> although the android app should work out of the box.

Does the scanner have a camera option? Or are you looking to run it just without barcode scanning?

**Comment by anonkwe** [comment]
@damien-ls you could compile it yourself even if the playstore would not be accessible, it is not such of a big deal

**Comment by damien-ls** [comment]
@anonkwe most open source project has their apk available. Not everybody are proficient into compiling android, has the toolchain, time, etc...

@SchrodingersGat the scanners input as a keyboard input, so all the fields can be used with some user input to select the field to scan on. Not the best but it's a good starting point already until some more specific app can be made.

**Comment by SchrodingersGat** [comment]
@damien-ls in https://github.com/inventree/inventree-app/pull/363 I have made some changes to allow for "custom" barcode scanning functionality.

What sort of scanner are you using? Maybe there is a way to capture the barcode input natively

**Comment by damien-ls** [comment]
@SchrodingersGat we just aim to scan internal barcode, not custom ones.

This is the one we use: https://bestsellergroupllc.com/index.php/product/caribe-pl-55l-handle-pda-android-8-1-barcode-scanner-1d-laser-2d-qr-code-portable-data-collector-device-with-grip/

Not sure if there is a native way to capture the barcode, but using emulated keyboard input is a more straightforward approach as most, if not all, barcode scanner has this feature. Native integration, given the thousands of barcode reader there are, will ever cover a fraction and each integration would require maintenance, (as we see for the label printer plugin of inventree only supports discontinued printers).

Any reason not to treat barcode reader just as keyboard input ?

**Comment by matmair** [comment]
@damien-ls there are label printing plugins for 50+ current zebra printers and any cups printer. Not sure where you get the feeling that we only support discontinued printers.

**Comment by damien-ls** [comment]
@matmair my bad, I was referring to the brother plugin in particular https://inventree.org/SchrodingersGat/inventree-brother-plugin

**Comment by SchrodingersGat** [comment]
I've opened a new issue for supporting barcode "wedge mode" - https://github.com/inventree/inventree-app/issues/364 - please keep any barcode related discussion there.

@damien-ls if you want to discuss printer support for the brother plugin, please raise a new issue over on that repo :)

With regard to uploading .apk - we can look into that.
