### ISSUE TITLE
Add ability to filter by stock status

### ISSUE THREAD

**Issue by dakaix** [inventree/inventree-app#374]
Ideally would like to be able to change the filtered view of stock in a location, to show items that may normally be hidden.

I use the "Quarantined" status to reflect items that are in-use, but their packaging is stored somewhere. Currently this status in the iOS app is not shown at all - and unlike the Web UI it's not possible to clear the filter for "In Stock" to then show everything.

**Comment by SchrodingersGat** [comment]
@dakaix makes sense to allow this filtering option to be customized!
