### ISSUE TITLE
[Bug] Label template drop-down is empty

### ISSUE THREAD

**Issue by simonkuehling** [inventree/inventree-app#398]
Just noticed a possible bug in the UI - for me in the label printing dialog of the app, the template selection drop-down is shown empty and cannot be opened for selection.

Label printing does work, though.

Screenshot:
![23-07-13 15-18-07 0062](https://github.com/inventree/inventree-app/assets/296454/0b845add-9866-4eee-a8aa-75820065d0c4)

App version:
0.12.2 - Build 68 on iPadOS 16.5.1

**Comment by SchrodingersGat** [comment]
@simonkuehling thanks for reporting. Some incoming updates in https://github.com/inventree/inventree-app/pull/399 - should address this I think

**Comment by simonkuehling** [comment]
Sweet - looking forward to that! :+1:

**Comment by simonkuehling** [comment]
@SchrodingersGat In iOS-Version 0.12.6 Build 73 the issue still seems to be there... 

![IMG_6260](https://github.com/inventree/inventree-app/assets/296454/7b69507c-0b57-4944-b6ed-5f751bbfc4f9)

**Comment by SchrodingersGat** [comment]
@simonkuehling OK I'll have to look into this further. What InvenTree server version are you running?

**Comment by simonkuehling** [comment]
The server is running 0.13.0 dev at 92b0a1927

```
# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.20

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.15.32-v7l+-armv7l-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'IPNAutoGenerator', 'slug': 'ipnautogenerator', 'version': None}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.7.0'}]
```

**Comment by SchrodingersGat** [comment]
@simonkuehling still struggling to reproduce this :)

- Are you printing a label for a "stock item"?
- Can you confirm that there are multiple label templates available?

**Comment by simonkuehling** [comment]
@SchrodingersGat Yes, I'm printing StockItem labels and there are two label templates activated in my instance.

If there is anything else I can provide, just let me know!

**Comment by SchrodingersGat** [comment]
Can you show the printing dialog from the web interface? In particular the "name" and "description" values for the label templates you have available?

**Comment by SchrodingersGat** [comment]
e.g. 
![image](https://github.com/inventree/inventree-app/assets/10080325/645076d9-f1a7-4ae0-aaee-2829bd7b08fe)

**Comment by simonkuehling** [comment]
Could be a german "Umlaut" issue, if you thought in that direction:

![image](https://github.com/inventree/inventree-app/assets/296454/d76d017d-042c-4d98-8b79-a414515d6237)

![image](https://github.com/inventree/inventree-app/assets/296454/3d6387cd-9c8e-4384-a358-5df3da2999c4)

**Comment by SchrodingersGat** [comment]
@simonkuehling your esoteric german characters don't seem to cause any issue :)

![image](https://github.com/inventree/inventree-app/assets/10080325/28ae4654-4163-4da5-8141-e9e4a03538a1)

**Comment by SchrodingersGat** [comment]
Oh wait - you have an empty description on those labels? Try adding a description value to each label and see if that fixes? Looking at the code, it only (currently) displays the description, and not the *name* of the label

**Comment by simonkuehling** [comment]
Good catch, that does something - I now get the list of label descriptions in the dropdown and it seems to print as well (cannot physically confirm right now, but I get the "label sent to printer confirmation")

There is no default selection, though - that would be a good idea I think.

**Comment by SchrodingersGat** [comment]
@simonkuehling ok I think that this is well understood and addressed now. Will issue a new release soon
