### ISSUE TITLE
[FR] App for mobile phone - Password for each user

### ISSUE THREAD

**Issue by RichiSeitz** [inventree/inventree-app#403]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

If you have more then one user in the app you can change the user how you want. So user A can do some things under the name of user B or in other direction.

### Suggested solution

If you could set a short password with, for example 4 digits, the problem would be done.

### Describe alternatives you've considered

I don´t know a other methode.

### Examples of other systems

0.12.5 July 2023 Android
0.12.5 July 2023 IOS

### Do you want to develop this?

- [X] I want to develop this.

**Comment by SchrodingersGat** [comment]
@RichiSeitz I have transferred this issue over to the "app" repository.

So currently the app provides the ability to switch between profiles. You are suggesting that you want this "profile switch" to be locked behind a password or passcode?

**Comment by RichiSeitz** [comment]
Hello,

oh sorry I didn´t see that there is a "app"repository. Yes that is exactly what I mean. Thank you

**Comment by SchrodingersGat** [comment]
@RichiSeitz after thinking about this further, can you address your problem by creating multiple profiles, for the same server, but with different users?
