### ISSUE TITLE
Missing Dependency? 

### ISSUE THREAD

**Issue by JackFGS** [inventree/inventree-app#406]
Im trying to compile in linux but get the following error:

<img width="591" alt="2023-07-24 15_34_38-localhost localdomain - VMware ESXi - Brave" src="https://github.com/inventree/inventree-app/assets/97601127/34719184-5e6d-4aed-98f9-0db4851c9586">

**Comment by SchrodingersGat** [comment]
You will either need to provide your own key for [sentry.io](https://sentry.io) or comment out the code which uses it
