### ISSUE TITLE
UPC-A barcodes

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-app#419]
I see that currently in the iOS app I can't scan UPC-A codes, but the same code in code-128 format is scanned fine.
Is there an ETA for reading a wider range of barcodes?

_Originally posted by @superbeppe98 in https://github.com/inventree/inventree-app/issues/294#issuecomment-1703934642_

**Comment by SchrodingersGat** [comment]
Currently we use the [qr_code_scanner](https://pub.dev/packages/qr_code_scanner) library which is now in maintenance mode. 

Perhaps there is a more modern library which also supports scanning of UPC-A codes?

**Comment by superbeppe98** [comment]
Seems that in [qr_code_scanner](https://pub.dev/packages/qr_code_scanner) the iOs version doesn't support the 1D barcodes, but in Android support 1D and 2D.

While I was looking for other libraries I saw this, seems the same author but it's new version: [mobile_scanner](https://pub.dev/packages/mobile_scanner)
I also saw this: [qr_flutter](https://pub.dev/packages/qr_flutter)

**Comment by SchrodingersGat** [comment]
`mobile_scanner` looks like it might be worth a further look :)

**Comment by SchrodingersGat** [comment]
Another potential library: https://pub.dev/packages/code_scan/

**Comment by 30350n** [comment]
The current library is also somewhat slow and unreliable, especially for datamatrix codes (atleast on my phone).

**Comment by SchrodingersGat** [comment]
@30350n finally updated to a newer library, should be much quicker and more reliable.

Ref: https://github.com/inventree/inventree-app/pull/562

**Comment by 30350n** [comment]
Nice! I've been quiet wound up with finishing my Bachelor's thesis lately, so I haven't been able to keep up with all the progress on InvenTree as much as I'd like :/

But I'll definitely test this out the next time I got a bunch of things I have to scan ^^
