### ISSUE TITLE
Statuses of stock or purchase orders not translating since  commit 26b86a2

### ISSUE THREAD

**Issue by anonkwe** [inventree/inventree-app#423]
isnt translating with iphone official app from appstore with demoserver as well.

![image](https://github.com/inventree/inventree-app/assets/61838766/43d6087d-beb0-4cb2-bdec-dfffac7a7bab)

![image](https://github.com/inventree/inventree-app/assets/61838766/7f2c2a28-19dc-438b-ab06-ea0b055cff80)

**Comment by SchrodingersGat** [comment]
@anonkwe thanks for pointing this out. It appears that both the "status codes" (for various models) and the form fields themselves are not being translated. Looks to be an issue with how the requests are being made from the app..

Will look into this tonight, should be an easy fix.

**Comment by matmair** [comment]
@SchrodingersGat this could be missing language headers

**Comment by SchrodingersGat** [comment]
> @SchrodingersGat this could be missing language headers

Yep, that's exactly what is happening. These requests are all being sent with `en_US` no matter what the selected locale on the app is.

**Comment by SchrodingersGat** [comment]
@anonkwe should be fixed now
