### ISSUE TITLE
Minimum OS Now Android 13?

### ISSUE THREAD

**Issue by rezafouladian** [inventree/inventree-app#425]
Was there a specific reason for changing the minimum Android version to Android 13 in 81907ad72f293fa73d9fa6bfe7ced2f985115695? The barcode scanning phones I'm trying to work with from Zebra and Datalogic only have Android 8, 9, 10, or 11.

**Comment by SchrodingersGat** [comment]
@rezafouladian if you look at [this website](https://apilevels.com/) you can see that the required `targetSdk` version was bumped to 33 for apps and app updates by August 2023. This is why I made the change.

However the same page further down suggests that the `minSdk` could be as low as 21 (Android 5)?

So, potentially we could adjust `minSdk` to be API level 26 (supporting Android 8) with a `targetSdk` level of 33 and still be in compliance?

The whole versioning system is very confusing...

**Comment by rezafouladian** [comment]
Yes, I believe the targetSdk version can be higher while leaving the minimum lower.

[https://developer.android.com/google/play/requirements/target-sdk](https://developer.android.com/google/play/requirements/target-sdk)
> Every new Android version introduces changes that bring security and performance improvements and enhance the Android user experience. Some of these changes only apply to apps that explicitly declare support through their targetSdkVersion manifest attribute (also known as the target API level).
> 
> Configuring your app to target a recent API level ensures that users can benefit from these improvements, while your app can still run on older Android versions.

**Comment by SchrodingersGat** [comment]
@rezafouladian please LMK if it works for you now
