### ISSUE TITLE
Refresh issues after any stock modification

### ISSUE THREAD

**Issue by anonkwe** [inventree/inventree-app#428]
Hey,

Just reporting an issue that I guess you guys are probably already aware of. after you modify stock (location, quantity or anything). You get back to the stock location's detailed list. Problem occuring is that users have to press the refresh button besides the filtering options for the list to get refreshed and to display the list including any modification that was made on any elements on the list. Not sure if it's a limitation of any sort, but I guess the normal behavior is that modifications are automatically pushed and the list is also automatically refreshed the moment modifications were made. 

not sure if you understand what I mean, i dont have my emulator running right now but if I'm not clear, please tell me and I'll provide visual support of the issue happenning.

**Comment by SchrodingersGat** [comment]
@anonkwe if you can provide a screencast of the issue, that would really help :)

**Comment by SchrodingersGat** [comment]
Closing due to lack of feedback
