### ISSUE TITLE
[FR] Scanner wedge mode - extend to all APP pages

### ISSUE THREAD

**Issue by 42CrMo4** [inventree/inventree-app#440]
I would like to propose extending the scanner wedge mode introduced in #437 to work in the APP without having to go into explicit scanner mode. 
This would improve usability and speed of operation.

**Comment by matmair** [comment]
Wouldn't that mean that the inventree app would always be streaming all keyboard inputs to the server? Seems like a security/privacy problem

**Comment by SchrodingersGat** [comment]
@matmair it is a good thought, worth considering:

> Wouldn't that mean that the inventree app would always be streaming all keyboard inputs to the server? 

Only on the *home* screen, which is not insignificant

It would be sending data to the default barcode "scan" API endpoint only. Still, if connected to a keyboard which is streaming in a lot of data, could potentially overwhelm the server

**Comment by 42CrMo4** [comment]
That is a valid point. I though the Lib is only streaming the data in case of a potential barcode (ASCII and fast enough not be human, according to the [readme](https://github.com/fuadreza/flutter_barcode_listener/blob/master/README.md#implementation-idea)). But if that is not the case it would be not a clean way.

**Comment by SchrodingersGat** [comment]
The barcode scanning mode is now accessible as a single-click button from *anywhere* in the app - so I am closing this out.
