### ISSUE TITLE
[FR] Fdroid Availability

### ISSUE THREAD

**Issue by darkdecoy** [inventree/inventree-app#445]
Any possibility of making this available in Fdroid or even just publishing an apk with new release?  Thanks.

**Comment by matmair** [comment]
That would a bit counter to the convenience fee that is currently attached to app on the stores. Or has Fdroid added a monetisation feature?

**Comment by darkdecoy** [comment]
I'm not aware of any monetisation features on Fdroid. Hadn't even looked at the Google play listing so didn't realize that it was cost anything.  I have been working to move away from anything tied to Google so really if there was a way to pay to get access to a simple apk download I might interested. Where I work is testing inventree out so not sure how much we are going to use so just looking at what options there would be to get the app without Google being involved.

**Comment by matmair** [comment]
Maybe throw an email to `support <AT> inventree <DOT> org` with your exact requirements and we might be able to help you out. You can throw me in CC if you want `code@mjmair.com`.

**Comment by SchrodingersGat** [comment]
If anyone is looking through these old issues, please note that we do offer a direct download for the app:

https://polar.sh/inventree/products/299bf0d5-af88-4e0f-becf-c007ad37ecf2
