### ISSUE TITLE
"Server error" on stock item deletion

### ISSUE THREAD

**Issue by chris-thorn** [inventree/inventree-app#449]
_App version 0.13.0 from Google Play Store_

When I remove all of a particular stock item, the Android app shows "Server error" in red at the bottom of the screen and the stock quantity remains the same until I refresh the data, at which point the stock item disappears.

This sounds [to me, a layman] like the behaviour described in issue #50 - though I don't know the error code of the "Server error" notification.

https://github.com/inventree/inventree-app/assets/3541291/a5f56549-637e-4cec-939b-32a69296592a

Hopefully this video demonstrates the issue. I remove all nine stock items of a particular bearing, which results in this "Server error".

**Comment by wolflu05** [comment]
Please provide more information like server version, server logs, ...

**Comment by chris-thorn** [comment]
Sorry about that!

# Version Information:
InvenTree-Version: 0.13.0 dev
Django Version: 3.2.23
Commit Hash: e6db817
Commit Date: 2023-11-10

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-5.10.0-26-amd64-x86_64-with
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}, {'name': 'InvenTreeCurrencyExchange', 'slug': 'inventreecurrencyexchange', 'version': '1.0.0'}, {'name': 'InvenTreeLabel', 'slug': 'inventreelabel', 'version': '1.0.0'}, {'name': 'InvenTreeLabelSheet', 'slug': 'inventreelabelsheet', 'version': '1.0.0'}, {'name': 'DigiKeyPlugin', 'slug': 'digikeyplugin', 'version': '1.0.0'}, {'name': 'LCSCPlugin', 'slug': 'lcscplugin', 'version': '1.0.0'}, {'name': 'MouserPlugin', 'slug': 'mouserplugin', 'version': '1.0.0'}, {'name': 'TMEPlugin', 'slug': 'tmeplugin', 'version': '1.0.0'}, {'name': 'Brother Labels', 'slug': 'brother', 'version': '0.8.0'}]

I'm afraid I cannot see in the docs how to provide logs from the app. There is no error recorded in **Errors** in the Admin interface.

If I click on **Details** in the **Server error** popup it says "Error fetching data from server".

Are you able to reproduce this behaviour?

Chris

**Comment by wolflu05** [comment]
~~No, I cannot reproduce this. To see server errors, you would need to look on your server for log files. Can you please also check if you have similar errors when using the web interface? It would also helpful to know which python version you are running on your server.~~

**Edit:** sorry, I'm now able to reproduce that. That must be an issue with the app @SchrodingersGat (I tested against the demo server)

**Comment by SchrodingersGat** [comment]
Yes, can reproduce this. The app does not currently handle the case where *all* of the stock is removed! I'll look into it
