### ISSUE TITLE
Suggestion: Receiving stock - expiry date

### ISSUE THREAD

**Issue by jamie-dallow** [inventree/inventree-app#457]
Hi, when receiving line items it would be useful to be able to add the expiry date (I can see you can enter batch/serial numbers), instead of having to receive then to go the stock item and edit to add the expiry date.

Thanks

**Comment by SchrodingersGat** [comment]
Hey @jamie-dallow this is currently a limitation of the [backend code](https://github.com/inventree/inventree) - not specifically the app. The API for receiving items does not expose the "expiry_date" field...

If you would like to discuss this further please first raise an issue over on the main code repo :)

**Comment by jamie-dallow** [comment]
Thanks @SchrodingersGat  - I thought I'd put it in the main one, sorry!
