### ISSUE TITLE
App Flow question.

### ISSUE THREAD

**Issue by CFox243** [inventree/inventree-app#480]
I'm trying to see if I'm understanding it wrong or if I have a setting incorrect on the server.

I planned to have all bins labeled and have QR code to location with people for their personal trucks.
scan bin label go to stock then scan to location and scan qr code that travels with them.

However when you click scan to location it transfers the whole stock instead of asking the amount to transfer is there a way to fix this on my end or is this the expected behavior and I'm just understanding the flow incorrectly?

expected behavior in my head.

scan bin QR in warehouse > go to stock scan to location > scan QR code on key-ring > pop up a new window how many to transfer with a default of 1.

thank you in advance

**Comment by SchrodingersGat** [comment]
@CFox243 good question. Currently the 'scan' behaviour does not let you jump in to adjust the quantity to be scanned - it simply transfers the entire quantity. 

I guess the adjusted behaviour could be either:

a) Always ask for quantity
b) Add a setting to determine whether it asks for quantity
c) Add a second barcode scan function called "Scan Quantity" (or similar) which asks for quantity

Thoughts?

**Comment by CFox243** [comment]
@SchrodingersGat 

sorry for the late response.

in this case option (B) would work just fine keeps one button as long as we can set it on the admin level and not per device.

on a side note though I think in a away it should always ask amount or at least state it's transferring the whole amount.
but I would ask for input outside of my use case I might be looking at it in a different use case than most.

thank you for your time on this.

**Comment by SchrodingersGat** [comment]
@CFox243 I think there is merit in adding this in and I am also leaning towards the idea of *always* forcing the user to select quantity to transfer. If you would like to submit a PR to implement this, that's great, otherwise you can contribute to this issue via the 'fund' button above :)

**Comment by SchrodingersGat** [comment]
@CFox243 fix incoming in https://github.com/inventree/inventree-app/pull/485 - now there is a global option to enable "confirmation" of stock transfers made via barcode scanning. If you do find this useful I would appreciate any small amount of funding for my time on this :)
