### ISSUE TITLE
Barcode Scan Error when Allocating Stock to sales order (#466)

### ISSUE THREAD

**Issue by timmyhadwen** [inventree/inventree-app#481]
Hi All,

We are using Inventree 0.14.4 and the allocate stock functionality is not working. I am getting Barcode Scan Error in orange at the bottom of the scan screen.

Steps:
Open app
Open Sales order
Click little QR code icon
Click Allocate stock
Scan stock item barcode
Error appears

Cheers
Tim

**Comment by SchrodingersGat** [comment]
@timmyhadwen some questions:

- What is the error? If the app does not display an error message, does the server?
- Can you provide a screenshot?
- What supplier barcode type are you scanning?

**Comment by timmyhadwen** [comment]
Error log:
10.0.10.143 - - [04/Apr/2024:05:05:14 +0000] "POST /api/barcode/so-allocate/ HTTP/1.0" 400 46 "-" "Dart/3.1 (dart:io)"

Screenshot: Unfortunately cannot click the little I to get more info as it closes just before the overlay ends.
![IMG_0952](https://github.com/inventree/inventree-app/assets/4350849/d0cdbf84-e3a5-40cf-91e4-33a5c633d955)

Photo of the barcode we are scanning. Should be a stock item. The QR Data is
```{"stockitem": 437}```
![IMG_0953](https://github.com/inventree/inventree-app/assets/4350849/faabc152-ef6c-4a14-b2f0-dd0bf33a8386)

**Comment by SchrodingersGat** [comment]
Any there any related logs available from the server side?

**Comment by timmyhadwen** [comment]
@SchrodingersGat Is there a particular log file that you think it might be in?

**Comment by timmyhadwen** [comment]
Closing this as it seems to be resolved in later versions.
