### ISSUE TITLE
Prevent sleep/lock while scanning 

### ISSUE THREAD

**Issue by j-huff** [inventree/inventree-app#492]
I think it would be better to prevent the phone from locking if you have the scanner/camera open. Really annoying to have to keep double tapping the screen to prevent my phone from locking.

**Comment by SchrodingersGat** [comment]
@j-huff good idea!

**Comment by j-huff** [comment]
On a related note, I find that the camera scanner has a difficult time focusing. Sometimes I'll have to close the camera and reopen it for it to refocus. There should either be a tap to focus feature, or make the automatic refocus more aggresive. 

Edit: Focus as in with the camera lens.

**Comment by SchrodingersGat** [comment]
@j-huff thanks for the input. We are already [considering a new barcode scanner library](https://github.com/inventree/inventree-app/issues/419) - so maybe there are better auto-focus options available.

**Comment by SchrodingersGat** [comment]
@j-huff finally got around to this one - https://github.com/inventree/inventree-app/pull/565
