### ISSUE TITLE
stock list, bug with names

### ISSUE THREAD

**Issue by spitdavid** [inventree/inventree-app#498]
![IMG_7858](https://github.com/inventree/inventree-app/assets/171500774/f08cf2a0-3109-4be8-a402-c3c42914ff72)
![IMG_7857](https://github.com/inventree/inventree-app/assets/171500774/6a070ce8-f57d-4f0f-86b9-a85e8939c203)
The names of the stock items are displayed incorrectly. iOS 17.5.1, latest version of the app

**Comment by SchrodingersGat** [comment]
I think this is happening because the serial number is so long and is pushing the width out to the entire screen.

**Comment by spitdavid** [comment]
Is there some way to fix it, except the option to shorten the SN?

**Comment by SchrodingersGat** [comment]
@spitdavid a fix is incoming in #499
