### ISSUE TITLE
Attachment Upload Error - and random attachments show in a purchase order

### ISSUE THREAD

**Issue by simonkuehling** [inventree/inventree-app#525]
I just upgraded our inventree server to the 0.17.0 dev @ 5515e07 version this week and cannot upload attachments to purchase orders or parts via the app (```0.16.1 - Build 88```) anymore. Also in at least one purchase order, there are attachments listed that have no relation to that purchase order and belong to a part...

The purchase order overview lists 4 attachments correctly:
<img src="https://github.com/user-attachments/assets/6abff917-215f-451c-bfde-23322a0b25e9" width="30%" height="30%">

but there are 6 files shown in the attachments list, two of them do not belong here and have no relation to the purchase order:
<img src="https://github.com/user-attachments/assets/c0988a33-8e8b-47aa-9bc6-792a88951fa4" width="30%" height="30%">

when uploading a new file, I get an error message that I unfortunately cannot grab the details of fast enough since the banner dissappears too quickly:
<img src="https://github.com/user-attachments/assets/19420ed2-021e-41c0-a98c-3665877c9aeb" width="30%" height="30%">

**Comment by SchrodingersGat** [comment]
@simonkuehling thanks for reporting, I'll look into it.

**Comment by SchrodingersGat** [comment]
@simonkuehling for reference, what is the API version of the InvenTree server you are running?

**Comment by SchrodingersGat** [comment]
Fix incoming in https://github.com/inventree/inventree-app/pull/528
