### ISSUE TITLE
Print error message

### ISSUE THREAD

**Issue by Philipboy881** [inventree/inventree-app#530]
When I print a label I get a green succes message (I print it to a real printer via the zebra print plugin)

The printer works and prints my label.

This is the following message:

![Screenshot_2024-09-12-09-18-21-79_b397d829b9781301e633e10148a0aac5.jpg](https://github.com/user-attachments/assets/f2f3ab8c-ba9c-48f0-be43-a11f217ccde5)

**Comment by SchrodingersGat** [comment]
@Philipboy881 so the printing does work, and the label is printed, just you also get this error message?

**Comment by Philipboy881** [comment]
Yes correct
