### ISSUE TITLE
Cannot print stockitem

### ISSUE THREAD

**Issue by Philipboy881** [inventree/inventree-app#531]
When I am in this location of the app (stockitem) it only wants to print stock location label instead of stockitem location label

![Screenshot_2024-09-12-09-19-07-47_b397d829b9781301e633e10148a0aac5.jpg](https://github.com/user-attachments/assets/eed2bceb-745c-4cad-889c-395fd3fe9ece)

![Screenshot_2024-09-12-09-28-55-85_b397d829b9781301e633e10148a0aac5.jpg](https://github.com/user-attachments/assets/dcd77ec4-fd8a-4f42-849c-63f96b6b11f6)

**Comment by SchrodingersGat** [comment]
@Philipboy881 thanks, there is a fix incoming - https://github.com/inventree/inventree-app/pull/533
