### ISSUE TITLE
Having trouble building the project

### ISSUE THREAD

**Issue by grammenoudis** [inventree/inventree-app#535]
I use the same version as the actions commands 

Flutter 3.13.0 • channel [user-branch] • unknown source
Framework • revision efbf63d9c6 (1 year, 1 month ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0

But I can't build the project, I follow the instructions (invoke translate, flutter pub get, invoke android) and i get this:
![Image](https://github.com/user-attachments/assets/1b94f319-1416-40f7-b4ca-70815af05cd4)

**Comment by SchrodingersGat** [comment]
Running `invoke android` is trying to build a signed executable. If you don't have signing setup, it will fail.

You can build an unsigned APK without issue. Also you can build and run via AndroidStudio without signin
