### ISSUE TITLE
Purchase Price can not be empty when creating new stock item

### ISSUE THREAD

**Issue by cbenhagen** [inventree/inventree-app#538]
When creating a new stock item the purchase price can not be empty and defaults to 0 which is not desirable.

![Image](https://github.com/user-attachments/assets/7216309d-a18c-416a-aae2-e6a9373ea5d5)

Tested on latest master branch (6c0b3cccc30d89e501bff4e560e2a53fc101ab0a)

**Comment by SchrodingersGat** [comment]
@cbenhagen thanks for reporting - fix incoming in https://github.com/inventree/inventree-app/pull/539

**Comment by cbenhagen** [comment]
Thanks @SchrodingersGat! #539 should solve the first part of this issue. I should have maybe created a second one for nullable fields defaulting to 0. When the dialog opens the field should default to an empty string if this is nullable right?

**Comment by cbenhagen** [comment]
@SchrodingersGat thanks again for the quick fix!! I just recompiled the app and it works as expected.
