### ISSUE TITLE
Lower limit for one-time GitHub Sponsors

### ISSUE THREAD

**Issue by ondras12345** [inventree/inventree-app#552]
Hi,
I don't want to buy the app on Google Play as I don't want Google to take a share of the transaction.
Thus, I built this awesome app from source and wanted to sponsor an amount equivalent to purchasing the app via GitHub Sponsors (which, if I understand correctly, does not take a cut of the transaction).
However, when trying to create a custom one-time sponsorship here https://github.com/sponsors/inventree?frequency=one-time, it tells me that "Amount must be at least $100".
It would be really nice if this lower limit on the amount could be lowered to match the app's cost. I don't need to "Get a shoutout on Twitter", I just want to support the project.

Alternatively, perhaps a one-time tier could be added that grants access to official APK builds (related: https://github.com/inventree/inventree-app/issues/445). I like to avoid Google services when installing open-source apps.

**Comment by matmair** [comment]
@SchrodingersGat this needs to be enabled in the sponsoring settings which only you have access to

**Comment by SchrodingersGat** [comment]
@ondras12345 with the new payment features provided by [polar.sh](https://polar.sh/inventree) we can now offer a one-time payment with a distributable `.apk` file behind a paywall.

I've set this up , please follow the link below and let me know if it works for you :)

https://polar.sh/inventree/products/299bf0d5-af88-4e0f-becf-c007ad37ecf2

**Comment by ondras12345** [comment]
Thanks!
I have purchased the app at polar.sh.
I will close this issue since there now is a suitable alternative to Google Play, although I still think you might benefit from removing the lower bound on Github Sponsors.
