### ISSUE TITLE
ASCII control characters in barcodes are erroneously substituted

### ISSUE THREAD

**Issue by ius** [inventree/inventree-app#570]
App version 0.17.0 substitutes ASCII control characters in barcodes for fancy unicode characters prior to submitting. For example, the ECIA/EIGP 114.2018 header `[)>\x1e06\x1d` ends up being POST'ed to `/api/barcode/` as `[)>␞06␝`.

(DigiKey) supplier part detection [relies](https://github.com/inventree/InvenTree/blob/master/src/backend/InvenTree/plugin/base/barcodes/mixins.py#L344-L348) on the original control characters being present (as per spec) so I guess this substitution is bogus. The app also displays the scanned barcode for debug purposes - displaying substitutes might make sense there.

**Additional information**
App version: 0.17.0 (built from source)
Flutter: 3.24.5

As a sidenote, I upgraded from 0.14.3 -> 0.17.0 as I ran into [#7637](https://github.com/inventree/InvenTree/issues/7637) but it seems like this very issue inadvertedly might serve as a workaround for that issue by virtue of breaking supplier part detection.

**Comment by SchrodingersGat** [comment]
@ius thanks for reporting. I have been able to reproduce this - fix incoming in https://github.com/inventree/inventree-app/pull/571
