### ISSUE TITLE
UniqueBarcodeHandler is broken due to supplier item matching

### ISSUE THREAD

**Issue by ius** [inventree/inventree-app#574]
Logic for assigning custom barcodes uses `UniqueBarcodeHandler` prior to actually linking the barcode to check whether a barcode is already in use.

https://github.com/inventree/inventree-app/blob/9745bcfdb6682d63584258e56f85c69da385dbbd/lib/barcode/barcode.dart#L383-L396

This uses the `/api/barcode/` endpoint which may in fact also return results due to the barcode being parsed and having an existing supplier item returned instead of the barcode actually being in use.

To reproduce: make sure a supplier item exists for a EIGP 114.2018 barcode (e.g. DigiKey/Mouser) then attempt to assign the barcode to a stock item.

I think this bug might be the cause of https://github.com/inventree/InvenTree/issues/7637

**Additional information**
App version: 0.17.0 (built from source + patched for #570)
Flutter: 3.24.5

**Comment by SchrodingersGat** [comment]
@ius nice catch - can you look into providing a patch for this?

**Comment by SchrodingersGat** [comment]
@ius I should have a fix a part of https://github.com/inventree/inventree-app/pull/577 - can you please test on your end and see if the issue is actually fixed?

**Comment by ius** [comment]
Was finally able to test this - works great! Thanks for the quick fix!
