### ISSUE TITLE
App sounds pause other media sources

### ISSUE THREAD

**Issue by Zennate** [inventree/inventree-app#582]
App Version: 0.17.1 - Build 93 on Android 11

Description:
When playing a sound through the app, it pauses other media sources (Spotify, VLC Media Player, etc.) that are running in the background. Pressing play on the affected source resumes play as expected.

Current Workaround:
Disabled all sounds in the app-settings.

**Comment by SchrodingersGat** [comment]
@Zennate that's an interesting one, not sure how we might address that. Perhaps you would be able to look into it?

- We use the [audioplayers](https://pub.dev/packages/audioplayers) package for playing audio
- Seems similar to the issue listed here - https://github.com/bluefireteam/audioplayers/issues/1497

**Comment by Zennate** [comment]
I can't really glean anything from the given examples, but with my limited knowledge on how this works, here's my idea.

Adding an [AudioContext](https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md#audio-context) in [helpers.dart](https://github.com/inventree/inventree-app/blob/51fb88985451333df56747430a8305305d930404/lib/helpers.dart#L100), which allows us to set [AndroidAudioFocus](https://pub.dev/documentation/audioplayers/latest/audioplayers/AndroidAudioFocus.html) to NONE should restore the expected behaviour, since it was set to GAIN by default in [this commit](https://github.com/bluefireteam/audioplayers/commit/858d3f4410b1bc7b203090c20cf60b5136dad4fe), with [this issue](https://github.com/bluefireteam/audioplayers/issues/1495) as context.

**Comment by SchrodingersGat** [comment]
@Zennate good insights, that seems to work a treat. Fix incoming in https://github.com/inventree/inventree-app/pull/583
