### ISSUE TITLE
[FR] Displaying expiration status of stock items

### ISSUE THREAD

**Issue by Zennate** [inventree/inventree-app#584]
The app currently cannot tell if a stock item is expired or not.
A basic implementation could check for the "expired" key in the API and display a small icon next to the quantity, similar to the web version.

**Comment by Zennate** [comment]
If I get the time to look into this project more, I'll try to create a PR for this feature myself.

**Comment by SchrodingersGat** [comment]
@Zennate LMK if you want any pointers on where to look in the code on this. It would be a good feature!
