### ISSUE TITLE
Print error

### ISSUE THREAD

**Issue by Philipboy881** [inventree/inventree-app#586]
I have a zebra printer connected to inventree via the zebra label printer plugin. Printing works perfectly but I get an error. Is it possible to not try to download the image when printing to a real printer 

![Screenshot_2024-12-22-22-12-34-16_b397d829b9781301e633e10148a0aac5.jpg](https://github.com/user-attachments/assets/446d67ce-7018-4cbe-a73a-c47acc492cd7)

**Comment by SchrodingersGat** [comment]
@Philipboy881 thanks for reporting this - fix is incoming in https://github.com/inventree/inventree-app/pull/587
