### ISSUE TITLE
Make handling arbitrary barcodes available from the barcode scanner

### ISSUE THREAD

**Issue by Guusggg** [inventree/inventree-app#63]
Relevant: #63 

Hi,

I thought of a cool feature I'm going to work on in this app. I want to be able to scan arbitrary barcodes and assign them to a stock.

When scanning a barcode that has no known match, the app will tell you it does not recognize it. I want to change this into the app telling you it is not recognized, but give you one of two options: 
- [ ] Create a new Stock Item with the existing barcode and it will ask which Part belongs to it.
- [ ] Check if there's existing Purchase orders with which you want to receive the item to.

What do you guys think? I'm creating this issue so I can create a branch associated to this feature, but any suggestions will be appreciated!

**Comment by SchrodingersGat** [comment]
I like this idea, I think it could work very well!

Are you aware that you can assign an arbitrary barcode to an *existing* stock item? I understand that this new feature would be to create a *new* stock item when scanning the barcode, which I think would be great

**Comment by Guusggg** [comment]
Exactly! I want to be able to scan boxes that come arrive here. I imagine this to be like:

1. Open the box to see what is inside
2. Scan the barcode on the box
3. The app will tell me it does not recognize the barcode, and it asks me if I want to assign it to a new stock item.

_I may need some more suggestions to build the above line out, as I think it will become a very powerful tool in 
checking in received items. Ideally the app would ask me if it's received from a particular Purchase Order and handle the Line Item Received for the Purchase Order that I tell the app it belongs to._

4. I set the Part to be the part that it is
5. The app will create a new stock item with an instantly assigned barcode, connected to the related Part

This will improve the workflow of my employer to be able to scan items that come in, check them in an leave them in the boxes for long time storage. (I have QR codes all over the place to then scan the item into a location)

Kind regards,

**Comment by SchrodingersGat** [comment]
Sounds pretty amazing! Please let me know if you have any queries about the inner workings of the app. In particular check out `api_form.dart` which makes procedural generated forms using the API!
