### ISSUE TITLE
Change stock status

### ISSUE THREAD

**Issue by Guusggg** [inventree/inventree-app#64]
Hi,

As a first test for me to get into the workflow of this app, I'm going to make a feature to change the stock status of a Stock Item.

- [ ] Probably make a DropdownField class to handle some logic of selecting a value from a DropdownButton.
- [ ] Look into the API on how to change the status of a Stock Item

If you have any feedback, I will appreciate it!

Kind regards,

**Comment by SchrodingersGat** [comment]
Check out the latest version - you can now edit stock items (which includes setting the "status"):

![image](https://user-images.githubusercontent.com/10080325/129642048-230850e0-fb56-4e89-8c8f-af262a70c021.png)

**Comment by Guusggg** [comment]
Perfect! Thanks a lot for the suggestion and it works perfect ^^
