### ISSUE TITLE
Scan in items to receive against a purchase order

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-app#66]
Need to implement a "purchase order" display for this first.

- Open the "purchase order" detail view
- Select a line item
- Select "scan in"
- Scan barcode of the received item
- Creates a new stock item linked to the correct part, linking back to the PO, and registering the scanned barcode

**Comment by Guusggg** [comment]
Hi,

Currently I'm working on this exact goal, however with a different approach.
What I have working right now is:
1. Open barcode scanner in home
2. Scan a unknown barcode
3. Select Receive Item from a popup dialog
3.1. I might put a Part selection before this
4. All purchase orders with this Part will be listed and you can select one of them
5. Line Item will be registered with the scanned barcode

Please tell me what you think.

Kind regards,

**Comment by SchrodingersGat** [comment]
I think having both approaches would work well - I definitely think they could both be implemented. I like your idea too!

**Comment by Guusggg** [comment]
I currently have it as:
1. Scan barcode that is unknown
2. Select the button to receive the item
3. The app will retrieve all items that are awaiting receiving, only unique parts.
3.1. When there's only one purchase order, go to 4.
3.2. When there's more than one purchase order, it shows the orders and you select the purchase order to receive it to.
4. The app will ask you how much you received and submit the information.

It might seem a bit bothersome but as I don't have too much knowledge about the project yet, I'm not sure if I can optimize this more. 

I think it's almost finished and I'm really curious to what you think about it.

Kind regards,

**Comment by SchrodingersGat** [comment]
I think the workflow sounds pretty reasonable - do you have a branch I can look at?

**Comment by Guusggg** [comment]
@SchrodingersGat I just created a DRAFT pullrequest so you can check out what's happening
#68

**Comment by SchrodingersGat** [comment]
Great! I'm away for the weekend but I'll check it out next week :)

**Comment by SchrodingersGat** [comment]
This feature has actually been implemented now
