### ISSUE TITLE
[launchApiForm] Purchase Order can not be submitted without requiring a scanned barcode

### ISSUE THREAD

**Issue by Guusggg** [inventree/inventree-app#78]
Hi,

Awesome work on the Receive features that landed recently! The whole overhaul of the app looks amazing too. 

Today, however, I upgraded to the new version of the app and the 0.5.1 tagged release of InvenTree. I wanted to try out the new Receive Line Items feature because I received items today. I noticed while trying to receive an item, it would greet me with an error where I need to enter a barcode. I looked into the source code and saw that you set the `"required"` property to `false` so I expect this is an error. 

Steps to reproduce:
1. Open the application and navigate to Purchase Orders.
2. Select a Purchase Order
3. Long press on a line item and tap `Receive Item`
4. Press submit on the top-right corner.
5. An error shows up saying: `Form Error`.

My first thought was that it must be an parse error however, I checked out the source and the `typeof` of the `"required"` field seems to be `bool` (correctly) so the `getParameter()` function from `APIField` functions correctly. 

Not sure how I can help you with this to be honest, would it be possible that the API returns a `String` and it incorrectly thinks the `"required"` property should be `true` because the `String` would not be empty? (I don't know too much about dart's internals to be honest...)

Thank you for your time and let me know if I can help you patch this up!

**Comment by SchrodingersGat** [comment]
This is a bug on the server end - I've just checked on `0.5.1` version and can confirm it's a bug. 

(The "latest" development version of InvenTree server works)

I'm pushing through a release `0.5.2` now which fixes this error - once that's out, update again and it should work for you :)

**Comment by SchrodingersGat** [comment]
@Guusggg 0.5.2 is out - update and let me know!

**Comment by Guusggg** [comment]
Perfect, works like a charm. Thanks for the ping!
