### ISSUE TITLE
Scan Into Location returns Status Code: 400

### ISSUE THREAD

**Issue by Guusggg** [inventree/inventree-app#80]
Hi,

Sorry to bother you today but I noticed an issue in the application, updated to the latest Google Play version (0.5.5) - Build 35.

When trying to move a box somewhere else and scanning the location, status code 400 is returned and the message "Item is not scanned into location" appears. 

I tested my location QR's, just to be sure, and they return the correct information in the app. When I scan the part individually, the app navigates to the correct page. My InvenTree instance is running on **0.6.0 dev**. 

Kind regards,

**Comment by SchrodingersGat** [comment]
I'll have to look into this one!

**Comment by SchrodingersGat** [comment]
Ok, worked it out, fix is at https://github.com/SchrodingersGat/inventreeapp/pull/82

**Comment by Guusggg** [comment]
Damn, thanks for your immense fast response and fix!

**Comment by SchrodingersGat** [comment]
No worries :) I'll try to get a new release out to the app store soon :)
