### ISSUE TITLE
[BUG] (minor) Multiline Text on Home Screen Widgets not centered (iOS)

### ISSUE THREAD

**Issue by simonkuehling** [inventree/inventree-app#98]
I see a layout inconsistency in the iOS apps home screen, where multi-line text on the widget buttons are not displayed centered:

<img src="https://user-images.githubusercontent.com/296454/164222244-64951e8d-aa3e-480d-96d7-71560ff4da21.png" width=300>

**Versions**
InvenTree iOS app version 0.5.6 - Build 36
iOS version 15.4.1 @ iPhone 12 Pro
iOS version 15.3.1 @ iPad Pro 12,9 5th Gen.

I can't find where the styling is done in the code, otherwise I would have been happy to prepare a PR instead...

**Comment by SchrodingersGat** [comment]
@simonkuehling yeah that does not look too nice at all!

I would *love* for you to submit a PR for this, currently I'm the only contributor to the app and it would be great to get someone else on board, even just to iron out the development wrinkles!

Each button on the home screen is created using this function:

https://github.com/inventree/inventree-app/blob/f34e9bb2aab4f373af726d52a3bfe7c223793288/lib/widget/home.dart#L172

So this will be a good starting point. Do you have any experience with Dart / Flutter?

I am more than happy to help you get setup for development, if we can work on a "developers guide" for the app that would encourage others to contribute also!

**Comment by simonkuehling** [comment]
> Each button on the home screen is created using this function:
> https://github.com/inventree/inventree-app/blob/f34e9bb2aab4f373af726d52a3bfe7c223793288/lib/widget/home.dart#L172
> So this will be a good starting point. Do you have any experience with Dart / Flutter?

Not in the slightest ;-) But that hasn't stopped me from digging into new territory before - I'm fluent in Google at the very least...

My quick guess would be to apply a `textAlign` property to the `Text(label)` widget in line 201 ...?:

```
  Widget _iconButton(BuildContext context, String label, IconData icon, {Function()? callback, String role = "", String permission = ""}) {

    bool connected = InvenTreeAPI().isConnected();

    bool allowed = true;

    if (role.isNotEmpty || permission.isNotEmpty) {
      allowed = InvenTreeAPI().checkPermission(role, permission);
    }

    return GestureDetector(
      child: Card(
        margin: EdgeInsets.symmetric(
          vertical: 10,
          horizontal: 10
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            FaIcon(
              icon,
              color: connected && allowed ? COLOR_CLICK : Colors.grey,
            ),
            Divider(
              height: 12,
              thickness: 0,
              color: Colors.transparent,
            ),
            Text(
              label,
              textAlign: TextAlign.center,                          <------------------------
            ),
          ]
        )
      ),
```

> I am more than happy to help you get setup for development, if we can work on a "developers guide" for the app that would encourage others to contribute also!

As much as I'm itching to dive right in, I don't quite have the time for a more serious commitment right now. But priorities can change very fast as I'm just starting to properly use InvenTree on a bigger scale. I'll be happy to come back to this when it happens.

**Comment by SchrodingersGat** [comment]
Fix incoming, was pretty simple as you thought. 

Do let me know if you have some time to contribute, either to the app or the web server!
